// GET /recipe/<token>  →  renders the customer's unlocked Recipe.
// The token was generated by stripe-webhook after payment and emailed to
// the customer. Records live in the "recipes" Blobs store forever.

import { connectLambda, getStore } from '@netlify/blobs';

export const handler = async (event) => {
  connectLambda(event);

  // Netlify passes the full path; we set up a splat redirect so /recipe/xyz
  // becomes /.netlify/functions/serve-recipe/xyz. Extract the token.
  const path = event.path || '';
  const match = path.match(/\/recipe\/([a-zA-Z0-9-]{10,80})/);
  const token = match ? match[1] : null;

  if (!token) {
    return htmlResponse(404, renderError('Missing recipe token', 'The link looks incomplete. Check the email we sent you and try again.'));
  }

  let record;
  try {
    record = await getStore('recipes').get(token, { type: 'json' });
  } catch (err) {
    console.error('[recipe] blobs error:', err.message);
    return htmlResponse(500, renderError('Storage error', 'Something on our side is broken. Please email andriybobchuk@gmail.com.'));
  }

  if (!record) {
    return htmlResponse(404, renderError('Recipe not found', "That link isn't in our system. If you just paid, wait 30 seconds and refresh."));
  }

  return htmlResponse(200, renderRecipe(record));
};

// ------------------------------------------------------------------
// HTML helpers — server-rendered, no client JS beyond copy buttons.
// ------------------------------------------------------------------
function htmlResponse(statusCode, body) {
  return {
    statusCode,
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Cache-Control': 'private, no-store',
      'X-Robots-Tag': 'noindex, nofollow',
    },
    body,
  };
}

function esc(s) {
  return String(s ?? '').replace(/[&<>"']/g, c => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  }[c]));
}

function renderError(title, message) {
  return `<!doctype html><html lang="en"><head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(title)} — Roast My LinkedIn</title>
${baseStyles()}
</head><body class="err">
<div class="wrap">
  <a class="brand" href="/" aria-label="Roast My LinkedIn — home">RoastMyLinkedIn</a>
  <h1>${esc(title)}</h1>
  <p>${esc(message)}</p>
  <a class="cta" href="/">← Back to the roast</a>
</div>
</body></html>`;
}

function renderRecipe(r) {
  const profile = r.profile || {};
  const audit = r.audit || {};
  const recipe = r.recipe || null;
  const err = r.recipeError;
  const name = profile.fullname || 'Your';
  const first = (name.split(' ')[0]) || 'Your';

  const bulletsSection = renderAllBullets(recipe?.all_bullets_rewritten);
  const featuredSection = renderFeaturedPosts(recipe?.featured_posts);
  const recsSection = renderRecommendationRequests(recipe?.recommendation_requests);
  const skillsSection = renderSkillsGap(recipe?.skills_gap);
  const coverSection = renderCoverLetter(recipe?.cover_letter);

  const safeFilename = (first || 'Your').replace(/[^a-zA-Z0-9-]/g, '') || 'Your';

  return `<!doctype html><html lang="en"><head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>${esc(first)}'s Recipe — Roast My LinkedIn</title>
<meta name="theme-color" content="#17130F">
<meta name="robots" content="noindex, nofollow">
${baseStyles()}
<script defer src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</head><body>
<div class="wrap" id="recipe-root">
  <header class="top">
    <a class="brand" href="/" aria-label="Roast My LinkedIn — home">RoastMyLinkedIn</a>
    <div class="top-actions">
      <span class="stamp">The Recipe · unlocked</span>
      <button class="pdf-btn" id="pdf-btn" onclick="downloadPDF()" aria-label="Download this Recipe as PDF">
        <span class="pdf-btn-label">Download PDF</span>
      </button>
    </div>
  </header>

  <div id="recipe-body">
    <section class="hero">
      <h1>${esc(first)}, your full Recipe is here.</h1>
      <p class="lede">Bookmark this URL. It's permanent, private, and always up to date. Download the PDF for offline access.</p>
      ${audit.score != null ? `<div class="score-row"><span class="score">${esc(audit.score)}</span><span class="outof">/ 100</span></div>` : ''}
      ${audit.summary ? `<blockquote class="summary">${esc(audit.summary)}</blockquote>` : ''}
    </section>

    ${err ? `<section class="alert"><p><strong>Heads up:</strong> the extended Recipe hit an error while generating (<code>${esc(err)}</code>). Reply to your receipt email and I'll fix this manually within a day.</p></section>` : ''}

    ${recipe ? bulletsSection : renderPending()}
    ${recipe ? featuredSection : ''}
    ${recipe ? recsSection : ''}
    ${recipe ? skillsSection : ''}
    ${recipe ? coverSection : ''}
  </div>

  <footer class="foot">
    <p>Roast My LinkedIn · Operated by Andrii Bobchuk, Warsaw.<br>
    Questions: <a href="mailto:andriybobchuk@gmail.com">andriybobchuk@gmail.com</a></p>
  </footer>
</div>

<script>
async function copy(btn, id) {
  const el = document.getElementById(id);
  if (!el) return;
  try { await navigator.clipboard.writeText(el.innerText); }
  catch { const ta = document.createElement('textarea'); ta.value = el.innerText; document.body.appendChild(ta); ta.select(); document.execCommand('copy'); ta.remove(); }
  const original = btn.textContent;
  btn.textContent = 'Copied ✓';
  btn.classList.add('copied');
  setTimeout(() => { btn.textContent = original; btn.classList.remove('copied'); }, 1500);
}

async function downloadPDF() {
  const btn = document.getElementById('pdf-btn');
  const label = btn.querySelector('.pdf-btn-label');
  if (typeof html2pdf === 'undefined') {
    label.textContent = 'PDF library still loading — try again in 2 seconds';
    return;
  }
  const orig = label.textContent;
  btn.disabled = true;
  label.textContent = 'Preparing PDF…';

  // Swap to a print/light theme for the PDF render so the file looks
  // like a real document, not a screenshot of a dark webpage.
  document.body.classList.add('pdf-mode');
  // Give the browser a paint tick to apply the class before html2canvas
  // reads computed styles.
  await new Promise(r => setTimeout(r, 60));

  try {
    const src = document.getElementById('recipe-body');
    await html2pdf().set({
      margin: [14, 14, 18, 14],
      filename: '${safeFilename}s-LinkedIn-Recipe.pdf',
      image: { type: 'jpeg', quality: 0.96 },
      html2canvas: { scale: 2, backgroundColor: '#FFFFFF', useCORS: true, logging: false, windowWidth: 900 },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
      pagebreak: { mode: ['css', 'legacy'], before: '.section' }
    }).from(src).save();
  } catch (e) {
    console.error('[pdf] generation failed:', e);
    alert('PDF generation failed. Try refreshing the page.');
  } finally {
    document.body.classList.remove('pdf-mode');
    btn.disabled = false;
    label.textContent = orig;
  }
}
</script>
</body></html>`;
}

function renderPending() {
  return `<section class="section">
    <div class="section-h"><span class="num">01</span><span class="title">Still cooking</span></div>
    <p>Your extended Recipe hasn't finished generating yet. Refresh this page in about 30 seconds — the sections below will appear as they're ready.</p>
  </section>`;
}

function renderAllBullets(byRole) {
  if (!Array.isArray(byRole) || !byRole.length) return '';
  const items = byRole.map((r, i) => {
    const rows = (r.bullets || []).map((b, bi) => {
      const id = `b-${i}-${bi}`;
      return `<div class="rewrite"><div class="rewrite-text" id="${id}">${esc(b)}</div><button class="copy" onclick="copy(this,'${id}')">Copy</button></div>`;
    }).join('');
    return `<div class="role-block"><h3>${esc(r.role || 'Role')}</h3>${rows}</div>`;
  }).join('');
  return `<section class="section">
    <div class="section-h"><span class="num">01</span><span class="title">Every bullet, rewritten</span></div>
    <p class="section-note">STAR format. Real facts only. Paste into LinkedIn's edit view.</p>
    ${items}
  </section>`;
}

function renderFeaturedPosts(posts) {
  if (!Array.isArray(posts) || !posts.length) return '';
  const items = posts.map((p, i) => {
    const id = `p-${i}`;
    return `<div class="post">
      <h3>${esc(p.title || 'Draft ' + (i + 1))}</h3>
      <div class="rewrite"><div class="rewrite-text" id="${id}">${esc(p.body || '')}</div><button class="copy" onclick="copy(this,'${id}')">Copy</button></div>
    </div>`;
  }).join('');
  return `<section class="section">
    <div class="section-h"><span class="num">02</span><span class="title">Five Featured post drafts</span></div>
    <p class="section-note">Pin these to your Featured section. Space them ~5-7 days apart. Recruiters read chronologically top-down.</p>
    ${items}
  </section>`;
}

function renderRecommendationRequests(reqs) {
  if (!Array.isArray(reqs) || !reqs.length) return '';
  const items = reqs.map((r, i) => {
    const id = `r-${i}`;
    return `<div class="post">
      <h3>${esc(r.target_relationship || 'Contact')}</h3>
      <div class="rewrite"><div class="rewrite-text" id="${id}"><strong>Subject:</strong> ${esc(r.subject || '')}\n\n${esc(r.body || '')}</div><button class="copy" onclick="copy(this,'${id}')">Copy</button></div>
    </div>`;
  }).join('');
  return `<section class="section">
    <div class="section-h"><span class="num">03</span><span class="title">Recommendation-request templates</span></div>
    <p class="section-note">Send from your personal email, not LinkedIn's default template. Response rate is 3-4× higher.</p>
    ${items}
  </section>`;
}

function renderSkillsGap(gap) {
  if (!gap || (!gap.missing_skills && !gap.commentary)) return '';
  const missing = Array.isArray(gap.missing_skills) ? gap.missing_skills.map(s => `<li>${esc(s)}</li>`).join('') : '';
  const path = Array.isArray(gap.learning_path) ? gap.learning_path.map(s => `<li>${esc(s)}</li>`).join('') : '';
  return `<section class="section">
    <div class="section-h"><span class="num">04</span><span class="title">Skills gap for your target role</span></div>
    ${gap.commentary ? `<p class="commentary">${esc(gap.commentary)}</p>` : ''}
    ${missing ? `<h3>Missing skills</h3><ul class="bullets">${missing}</ul>` : ''}
    ${path ? `<h3>Learning path</h3><ol class="bullets">${path}</ol>` : ''}
  </section>`;
}

function renderCoverLetter(cl) {
  if (!cl) return '';
  const id = 'cover';
  const body = [cl.opening_paragraph, cl.middle_paragraph, cl.closing_paragraph]
    .filter(Boolean).map(esc).join('\n\n');
  return `<section class="section">
    <div class="section-h"><span class="num">05</span><span class="title">Cover letter template</span></div>
    ${cl.notes ? `<p class="section-note">${esc(cl.notes)}</p>` : ''}
    <div class="rewrite"><div class="rewrite-text" id="${id}">${body}</div><button class="copy" onclick="copy(this,'${id}')">Copy</button></div>
  </section>`;
}

function baseStyles() {
  return `<style>
:root{--bg:#17130F;--ink:#080605;--fg:#F1EBDF;--fg-dim:rgba(241,235,223,.72);--fg-faint:rgba(241,235,223,.45);--amber:#D4A574}
*{box-sizing:border-box;margin:0;padding:0}
body{background:var(--bg);color:var(--fg);font-family:-apple-system,BlinkMacSystemFont,'SF Pro Display','Segoe UI',Helvetica,Arial,sans-serif;line-height:1.55;-webkit-font-smoothing:antialiased;letter-spacing:-.01em}
body.err{display:flex;align-items:center;justify-content:center;min-height:100vh;text-align:center;padding:24px}
.wrap{max-width:760px;margin:0 auto;padding:20px 20px 80px}
.top{display:flex;justify-content:space-between;align-items:center;padding:8px 0 24px;border-bottom:1px solid rgba(241,235,223,.14);margin-bottom:32px;gap:12px;flex-wrap:wrap}
.top-actions{display:flex;align-items:center;gap:14px}
.brand{background:var(--ink);color:var(--fg);padding:9px 12px 8px;font-weight:900;font-size:14px;letter-spacing:-.01em;line-height:1;display:inline-block;transform:rotate(-2.5deg);text-decoration:none;transition:transform .15s ease}
.brand:hover{transform:rotate(-1deg) translateY(-1px)}
.stamp{font-family:ui-monospace,'SF Mono',monospace;font-size:10px;letter-spacing:.22em;text-transform:uppercase;color:var(--amber);font-weight:800}
.pdf-btn{background:var(--amber);color:var(--ink);border:none;padding:10px 16px;font-weight:800;font-size:12px;letter-spacing:.08em;text-transform:uppercase;cursor:pointer;transition:transform .15s ease,background .15s ease;white-space:nowrap}
.pdf-btn:hover:not(:disabled){transform:translateY(-1px);background:var(--fg)}
.pdf-btn:disabled{opacity:.6;cursor:wait}
@media (max-width:520px){.top-actions{width:100%;justify-content:space-between}}

/* --- PDF export mode: temporarily flatten to a printable light theme so
     html2pdf produces a document that looks intentional on white paper. --- */
body.pdf-mode{background:#FFFFFF!important;color:#0B0806!important}
body.pdf-mode .wrap{max-width:none;padding:0}
body.pdf-mode .top{border-bottom-color:#D4A574;padding-bottom:14px}
body.pdf-mode .brand{background:#0B0806;color:#F1EBDF}
body.pdf-mode .stamp{color:#8C6D3F}
body.pdf-mode .pdf-btn{display:none}
body.pdf-mode h1,body.pdf-mode h2,body.pdf-mode h3{color:#0B0806}
body.pdf-mode .lede,body.pdf-mode .section-note,body.pdf-mode .bullets,body.pdf-mode .commentary{color:#3B3128}
body.pdf-mode .outof{color:#8C6D3F}
body.pdf-mode .summary{color:#3B3128;border-left-color:#D4A574}
body.pdf-mode .section{border-top-color:#E4D5B8;page-break-inside:avoid;break-inside:avoid}
body.pdf-mode .section-h .num{color:#8C6D3F}
body.pdf-mode .role-block h3{color:#8C6D3F}
body.pdf-mode .rewrite{background:#FBF7ED;color:#0B0806;box-shadow:none;border:1px solid #E4D5B8;page-break-inside:avoid;break-inside:avoid}
body.pdf-mode .copy{display:none}
body.pdf-mode .alert{background:#FDECE6;border-color:#E0492B;color:#0B0806}
body.pdf-mode .alert code{background:#FFFFFF;color:#0B0806}
body.pdf-mode .foot{color:#6B5C4A;border-top-color:#E4D5B8}
body.pdf-mode .foot a{color:#8C6D3F}
h1{font-size:clamp(30px,6vw,44px);font-weight:800;letter-spacing:-.03em;line-height:1.05;margin-bottom:14px}
.hero .lede{font-size:16px;color:var(--fg-dim);max-width:44ch;margin-bottom:20px}
.score-row{display:inline-flex;align-items:baseline;gap:8px;margin-bottom:16px}
.score{font-size:80px;font-weight:900;letter-spacing:-.05em;line-height:.9}
.outof{font-family:ui-monospace,'SF Mono',monospace;font-size:11px;letter-spacing:.22em;text-transform:uppercase;color:var(--fg-faint)}
.summary{font-family:Georgia,'Iowan Old Style',serif;font-style:italic;font-size:18px;line-height:1.5;color:var(--fg-dim);padding:16px 0;border-left:2px solid var(--amber);padding-left:16px;margin-top:12px}
.alert{background:rgba(224,73,43,.14);border:1px solid rgba(224,73,43,.35);padding:14px 18px;margin:28px 0;font-size:14px;color:var(--fg)}
.alert code{font-family:ui-monospace,monospace;font-size:12px;background:rgba(0,0,0,.3);padding:2px 6px}
.section{padding:44px 0;border-top:1px solid rgba(241,235,223,.14)}
.section-h{display:flex;align-items:baseline;gap:14px;margin-bottom:18px}
.section-h .num{font-family:ui-monospace,'SF Mono',monospace;font-size:11px;font-weight:800;letter-spacing:.28em;color:var(--amber)}
.section-h .title{font-size:22px;font-weight:800;letter-spacing:-.02em}
.section-note{color:var(--fg-dim);font-size:14px;margin-bottom:20px;max-width:52ch}
.role-block{margin-bottom:26px}
.role-block h3{font-size:15px;font-weight:800;letter-spacing:-.005em;text-transform:uppercase;color:var(--amber);letter-spacing:.14em;font-size:11px;margin-bottom:12px}
.post{margin-bottom:22px}
.post h3{font-size:16px;font-weight:800;margin-bottom:8px}
.rewrite{background:var(--fg);color:var(--ink);padding:18px 20px;margin-bottom:14px;box-shadow:6px 6px 0 rgba(0,0,0,.55);position:relative}
.rewrite-text{font-size:15px;line-height:1.55;white-space:pre-wrap}
.copy{position:absolute;top:12px;right:12px;background:var(--ink);color:var(--amber);border:none;padding:8px 12px;font-family:ui-monospace,monospace;font-size:10px;font-weight:800;letter-spacing:.16em;text-transform:uppercase;cursor:pointer}
.copy:hover{background:#000}
.copy.copied{background:#4A7C59;color:var(--fg)}
.bullets{padding-left:20px;color:var(--fg-dim);font-size:15px;margin-bottom:20px}
.bullets li{margin-bottom:6px;line-height:1.5}
.commentary{font-family:Georgia,serif;font-style:italic;font-size:16px;color:var(--fg-dim);max-width:52ch;margin-bottom:20px}
.cta{display:inline-block;padding:14px 22px;background:var(--amber);color:var(--ink);text-decoration:none;font-weight:800;margin-top:18px}
.foot{margin-top:60px;padding-top:28px;border-top:1px solid rgba(241,235,223,.14);font-size:12px;color:var(--fg-faint);text-align:center}
.foot a{color:var(--fg-dim)}
@media (min-width:720px){.wrap{padding:32px 24px 120px}h1{font-size:56px}.top{padding:16px 0 32px}}
</style>`;
}
