// GET /recipe/<token>  →  renders the customer's unlocked Recipe.
// The token was generated by stripe-webhook after payment and emailed to
// the customer. Records live in the "recipes" Blobs store forever.

import { connectLambda, getStore } from '@netlify/blobs';

export const handler = async (event) => {
  connectLambda(event);

  // Netlify passes the full path; we set up a splat redirect so /recipe/xyz
  // becomes /.netlify/functions/serve-recipe/xyz. Extract the token.
  const path = event.path || '';
  const match = path.match(/\/recipe\/([a-zA-Z0-9-]{10,80})/);
  const token = match ? match[1] : null;

  if (!token) {
    return htmlResponse(404, renderError('Missing recipe token', 'The link looks incomplete. Check the email we sent you and try again.'));
  }

  let record;
  try {
    record = await getStore('recipes').get(token, { type: 'json' });
  } catch (err) {
    console.error('[recipe] blobs error:', err.message);
    return htmlResponse(500, renderError('Storage error', 'Something on our side is broken. Please email andriybobchuk@gmail.com.'));
  }

  if (!record) {
    return htmlResponse(404, renderError('Recipe not found', "That link isn't in our system. If you just paid, wait 30 seconds and refresh."));
  }

  return htmlResponse(200, renderRecipe(record));
};

// ------------------------------------------------------------------
// HTML helpers — server-rendered, no client JS beyond copy buttons.
// ------------------------------------------------------------------
function htmlResponse(statusCode, body) {
  return {
    statusCode,
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Cache-Control': 'private, no-store',
      'X-Robots-Tag': 'noindex, nofollow',
    },
    body,
  };
}

function esc(s) {
  return String(s ?? '').replace(/[&<>"']/g, c => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  }[c]));
}

function renderError(title, message) {
  return `<!doctype html><html lang="en"><head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(title)} — Roast My LinkedIn</title>
${baseStyles()}
</head><body class="err">
<div class="wrap">
  <a class="brand" href="/" aria-label="Roast My LinkedIn — home">RoastMyLinkedIn</a>
  <h1>${esc(title)}</h1>
  <p>${esc(message)}</p>
  <a class="cta" href="/">← Back to the roast</a>
</div>
</body></html>`;
}

function renderRecipe(r) {
  const profile = r.profile || {};
  const audit = r.audit || {};
  const recipe = r.recipe || null;
  const err = r.recipeError;
  const name = profile.fullname || 'Your';
  const first = (name.split(' ')[0]) || 'Your';

  const scoreBreakdownSection = renderScoreBreakdown(recipe?.score_breakdown);
  const headlineVariantsSection = renderHeadlineVariants(recipe?.headline_variants);
  const aboutFullSection = renderAboutFull(recipe?.about_full_rewrite);
  const interviewPrepSection = renderInterviewPrep(recipe?.interview_prep);
  const recruiterVisibilitySection = renderRecruiterVisibility(recipe?.recruiter_visibility);
  const bulletsSection = renderAllBullets(recipe?.all_bullets_rewritten);
  const featuredSection = renderFeaturedPosts(recipe?.featured_posts);
  const recsSection = renderRecommendationRequests(recipe?.recommendation_requests);
  const skillsSection = renderSkillsGap(recipe?.skills_gap);
  const coverSection = renderCoverLetter(recipe?.cover_letter);

  const safeFilename = (first || 'Your').replace(/[^a-zA-Z0-9-]/g, '') || 'Your';

  return `<!doctype html><html lang="en"><head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>${esc(first)}'s Recipe — Roast My LinkedIn</title>
<meta name="theme-color" content="#17130F">
<meta name="robots" content="noindex, nofollow">
${baseStyles()}
<script src="/track.js" defer></script>
</head><body>
<div class="wrap" id="recipe-root">
  <header class="top">
    <a class="brand" href="/" aria-label="Roast My LinkedIn — home">RoastMyLinkedIn</a>
    <div class="top-actions">
      <span class="stamp">The Recipe · unlocked</span>
      <button class="pdf-btn" id="pdf-btn" onclick="downloadPDF()" aria-label="Download this Recipe as PDF">
        <span class="pdf-btn-label">Download PDF</span>
      </button>
    </div>
  </header>

  <div id="recipe-body">
    <section class="hero">
      <h1>${esc(first)}, your full Recipe is here.</h1>
      <p class="lede">Bookmark this URL. It's permanent, private, and always up to date. Download the PDF for offline access.</p>
      ${audit.score != null ? `<div class="score-row"><span class="score">${esc(audit.score)}</span><span class="outof">/ 100</span></div>` : ''}
      ${audit.summary ? `<blockquote class="summary">${esc(audit.summary)}</blockquote>` : ''}
    </section>

    ${err ? `<section class="alert"><p><strong>Heads up:</strong> the extended Recipe hit an error while generating (<code>${esc(err)}</code>). Reply to your receipt email and I'll fix this manually within a day.</p></section>` : ''}

    ${recipe ? scoreBreakdownSection : renderPending()}
    ${recipe ? headlineVariantsSection : ''}
    ${recipe ? aboutFullSection : ''}
    ${recipe ? interviewPrepSection : ''}
    ${recipe ? recruiterVisibilitySection : ''}
    ${recipe ? bulletsSection : ''}
    ${recipe ? featuredSection : ''}
    ${recipe ? recsSection : ''}
    ${recipe ? skillsSection : ''}
    ${recipe ? coverSection : ''}
  </div>

  <footer class="foot">
    <p>Roast My LinkedIn · Operated by Andrii Bobchuk, Warsaw.<br>
    Questions: <a href="mailto:andriybobchuk@gmail.com">andriybobchuk@gmail.com</a></p>
  </footer>
</div>

<script>
async function copy(btn, id) {
  const el = document.getElementById(id);
  if (!el) return;
  try { await navigator.clipboard.writeText(el.innerText); }
  catch { const ta = document.createElement('textarea'); ta.value = el.innerText; document.body.appendChild(ta); ta.select(); document.execCommand('copy'); ta.remove(); }
  const original = btn.textContent;
  btn.textContent = 'Copied ✓';
  btn.classList.add('copied');
  setTimeout(() => { btn.textContent = original; btn.classList.remove('copied'); }, 1500);
}

function downloadPDF() {
  if (window.rml) window.rml('pdf_download');
  // The page has a full @media print stylesheet that flips to a
  // light theme and hides chrome; the browser's print-to-PDF pipeline
  // (Save as PDF on Chrome/Safari/Firefox) is the destination.
  // Title override so the default filename in the print dialog isn't
  // ugly. Reverted after the dialog closes.
  const origTitle = document.title;
  document.title = '${safeFilename}s-LinkedIn-Recipe';
  window.print();
  // Restore on the next tick so print dialog has already captured it.
  setTimeout(() => { document.title = origTitle; }, 500);
}

// Fire recipe_view once track.js is loaded (defer means it lands after
// DOMContentLoaded). The recipeToken lets you join to the earlier session
// that ran the audit — same customer, same funnel.
document.addEventListener('DOMContentLoaded', () => {
  setTimeout(() => {
    if (window.rml) window.rml('recipe_view', { recipeToken: location.pathname.split('/').pop() });
  }, 100);
});
</script>
</body></html>`;
}

function renderPending() {
  return `<section class="section">
    <div class="section-h"><span class="num">01</span><span class="title">Still cooking</span></div>
    <p>Your extended Recipe hasn't finished generating yet. Refresh this page in about 30 seconds — the sections below will appear as they're ready.</p>
  </section>`;
}

function renderAllBullets(byRole) {
  if (!Array.isArray(byRole) || !byRole.length) return '';
  const items = byRole.map((r, i) => {
    const rows = (r.bullets || []).map((b, bi) => {
      const id = `b-${i}-${bi}`;
      return `<div class="rewrite"><div class="rewrite-text" id="${id}">${esc(b)}</div><button class="copy" onclick="copy(this,'${id}')">Copy</button></div>`;
    }).join('');
    return `<div class="role-block"><h3>${esc(r.role || 'Role')}</h3>${rows}</div>`;
  }).join('');
  return `<section class="section">
    <div class="section-h"><span class="num">06</span><span class="title">Every bullet, rewritten</span></div>
    <p class="section-note">STAR format. Real facts only. Paste into LinkedIn's edit view.</p>
    ${items}
  </section>`;
}

function renderFeaturedPosts(posts) {
  if (!Array.isArray(posts) || !posts.length) return '';
  const items = posts.map((p, i) => {
    const id = `p-${i}`;
    return `<div class="post">
      <h3>${esc(p.title || 'Draft ' + (i + 1))}</h3>
      <div class="rewrite"><div class="rewrite-text" id="${id}">${esc(p.body || '')}</div><button class="copy" onclick="copy(this,'${id}')">Copy</button></div>
    </div>`;
  }).join('');
  return `<section class="section">
    <div class="section-h"><span class="num">07</span><span class="title">Five Featured post drafts</span></div>
    <p class="section-note">Pin these to your Featured section. Space them ~5-7 days apart. Recruiters read chronologically top-down.</p>
    ${items}
  </section>`;
}

function renderRecommendationRequests(reqs) {
  if (!Array.isArray(reqs) || !reqs.length) return '';
  const items = reqs.map((r, i) => {
    const id = `r-${i}`;
    return `<div class="post">
      <h3>${esc(r.target_relationship || 'Contact')}</h3>
      <div class="rewrite"><div class="rewrite-text" id="${id}"><strong>Subject:</strong> ${esc(r.subject || '')}\n\n${esc(r.body || '')}</div><button class="copy" onclick="copy(this,'${id}')">Copy</button></div>
    </div>`;
  }).join('');
  return `<section class="section">
    <div class="section-h"><span class="num">08</span><span class="title">Recommendation-request templates</span></div>
    <p class="section-note">Send from your personal email, not LinkedIn's default template. Response rate is 3-4× higher.</p>
    ${items}
  </section>`;
}

function renderSkillsGap(gap) {
  if (!gap || (!gap.missing_skills && !gap.commentary)) return '';
  const missing = Array.isArray(gap.missing_skills) ? gap.missing_skills.map(s => `<li>${esc(s)}</li>`).join('') : '';
  const path = Array.isArray(gap.learning_path) ? gap.learning_path.map(s => `<li>${esc(s)}</li>`).join('') : '';
  return `<section class="section">
    <div class="section-h"><span class="num">09</span><span class="title">Skills gap for your target role</span></div>
    ${gap.commentary ? `<p class="commentary">${esc(gap.commentary)}</p>` : ''}
    ${missing ? `<h3>Missing skills</h3><ul class="bullets">${missing}</ul>` : ''}
    ${path ? `<h3>Learning path</h3><ol class="bullets">${path}</ol>` : ''}
  </section>`;
}

function renderCoverLetter(cl) {
  if (!cl) return '';
  const id = 'cover';
  const body = [cl.opening_paragraph, cl.middle_paragraph, cl.closing_paragraph]
    .filter(Boolean).map(esc).join('\n\n');
  return `<section class="section">
    <div class="section-h"><span class="num">10</span><span class="title">Cover letter template</span></div>
    ${cl.notes ? `<p class="section-note">${esc(cl.notes)}</p>` : ''}
    <div class="rewrite"><div class="rewrite-text" id="${id}">${body}</div><button class="copy" onclick="copy(this,'${id}')">Copy</button></div>
  </section>`;
}

// ---- New Tier-1 sections ------------------------------------------

function renderScoreBreakdown(sb) {
  if (!sb || !Array.isArray(sb.dimensions) || !sb.dimensions.length) return '';
  const rows = sb.dimensions.map(d => {
    const score = Math.max(0, Math.min(100, Number(d.score) || 0));
    const fixes = Array.isArray(d.fixes) ? d.fixes.map(f => `<li>${esc(f)}</li>`).join('') : '';
    return `<div class="dim">
      <div class="dim-head">
        <span class="dim-name">${esc(d.name || '')}</span>
        <span class="dim-score">${score}<span class="dim-slash">/100</span></span>
      </div>
      <div class="dim-bar"><div class="dim-bar-fill" style="width:${score}%"></div></div>
      ${d.commentary ? `<p class="dim-commentary">${esc(d.commentary)}</p>` : ''}
      ${fixes ? `<ul class="dim-fixes">${fixes}</ul>` : ''}
    </div>`;
  }).join('');
  return `<section class="section">
    <div class="section-h"><span class="num">01</span><span class="title">Score breakdown across six axes</span></div>
    <p class="section-note">Where your overall number actually comes from. Fix the low ones — they compound fastest.</p>
    <div class="dim-grid">${rows}</div>
  </section>`;
}

function renderHeadlineVariants(variants) {
  if (!Array.isArray(variants) || !variants.length) return '';
  const items = variants.map((v, i) => {
    const id = `hv-${i}`;
    return `<div class="variant">
      <div class="variant-angle">${esc(v.angle || 'Variant ' + (i + 1))}</div>
      <div class="rewrite"><div class="rewrite-text" id="${id}">${esc(v.text || '')}</div><button class="copy" onclick="copy(this,'${id}')">Copy</button></div>
      ${v.why ? `<p class="variant-why">${esc(v.why)}</p>` : ''}
    </div>`;
  }).join('');
  return `<section class="section">
    <div class="section-h"><span class="num">02</span><span class="title">Five headline variants to A/B</span></div>
    <p class="section-note">Different frames for different rooms. Rotate them monthly and watch which one gets the most InMail.</p>
    ${items}
  </section>`;
}

function renderAboutFull(af) {
  if (!af) return '';
  const id = 'about-full';
  const main = [af.opening_paragraph, af.middle_paragraph, af.closing_paragraph]
    .filter(Boolean).map(esc).join('\n\n');
  const alts = Array.isArray(af.alternative_openings) ? af.alternative_openings : [];
  const altItems = alts.map((a, i) => {
    const aid = `about-alt-${i}`;
    return `<div class="rewrite"><div class="rewrite-text" id="${aid}">${esc(a)}</div><button class="copy" onclick="copy(this,'${aid}')">Copy</button></div>`;
  }).join('');
  return `<section class="section">
    <div class="section-h"><span class="num">03</span><span class="title">Full About section — three-paragraph rewrite</span></div>
    <p class="section-note">Replace your entire About with this. Then A/B the opening against the alternates below.</p>
    <div class="rewrite"><div class="rewrite-text" id="${id}">${main}</div><button class="copy" onclick="copy(this,'${id}')">Copy</button></div>
    ${alts.length ? `<h3 class="sub-h">Alternative openings</h3>${altItems}` : ''}
  </section>`;
}

function renderInterviewPrep(prep) {
  if (!Array.isArray(prep) || !prep.length) return '';
  const items = prep.map((q, i) => {
    const id = `iq-${i}`;
    return `<div class="iq">
      <div class="iq-q">Q${i + 1}. ${esc(q.question || '')}</div>
      <div class="rewrite"><div class="rewrite-text" id="${id}">${esc(q.answer || '')}</div><button class="copy" onclick="copy(this,'${id}')">Copy</button></div>
      ${q.grounded_in ? `<p class="iq-grounded">Grounded in: ${esc(q.grounded_in)}</p>` : ''}
    </div>`;
  }).join('');
  return `<section class="section">
    <div class="section-h"><span class="num">04</span><span class="title">Interview-prep bank — ten STAR answers</span></div>
    <p class="section-note">Behavioral prompts pre-answered using your real projects. Read out loud twice each and they're yours.</p>
    ${items}
  </section>`;
}

function renderRecruiterVisibility(rv) {
  if (!rv || !Array.isArray(rv.keywords) || !rv.keywords.length) return '';
  const rows = rv.keywords.map(k => {
    const badge = k.currently_visible
      ? `<span class="vis-badge on">Surfaces</span>`
      : `<span class="vis-badge off">Misses</span>`;
    return `<div class="kw">
      <div class="kw-head"><span class="kw-word">${esc(k.keyword || '')}</span>${badge}</div>
      ${k.reasoning ? `<p class="kw-reason">${esc(k.reasoning)}</p>` : ''}
      ${k.fix ? `<p class="kw-fix"><strong>Fix:</strong> ${esc(k.fix)}</p>` : ''}
    </div>`;
  }).join('');
  const top = Array.isArray(rv.top_missing_keywords) ? rv.top_missing_keywords : [];
  return `<section class="section">
    <div class="section-h"><span class="num">05</span><span class="title">Recruiter search visibility</span></div>
    <p class="section-note">What a recruiter types into LinkedIn search and whether your profile surfaces. The keyword additions below plug the misses.</p>
    ${rows}
    ${top.length ? `<h3 class="sub-h">Top missing keywords to add</h3><ul class="bullets">${top.map(t => `<li>${esc(t)}</li>`).join('')}</ul>` : ''}
  </section>`;
}

function baseStyles() {
  return `<style>
:root{--bg:#17130F;--ink:#080605;--fg:#F1EBDF;--fg-dim:rgba(241,235,223,.72);--fg-faint:rgba(241,235,223,.45);--amber:#D4A574}
*{box-sizing:border-box;margin:0;padding:0}
body{background:var(--bg);color:var(--fg);font-family:-apple-system,BlinkMacSystemFont,'SF Pro Display','Segoe UI',Helvetica,Arial,sans-serif;line-height:1.55;-webkit-font-smoothing:antialiased;letter-spacing:-.01em}
body.err{display:flex;align-items:center;justify-content:center;min-height:100vh;text-align:center;padding:24px}
.wrap{max-width:760px;margin:0 auto;padding:20px 20px 80px}
.top{display:flex;justify-content:space-between;align-items:center;padding:8px 0 24px;border-bottom:1px solid rgba(241,235,223,.14);margin-bottom:32px;gap:12px;flex-wrap:wrap}
.top-actions{display:flex;align-items:center;gap:14px}
.brand{background:var(--ink);color:var(--fg);padding:9px 12px 8px;font-weight:900;font-size:14px;letter-spacing:-.01em;line-height:1;display:inline-block;transform:rotate(-2.5deg);text-decoration:none;transition:transform .15s ease}
.brand:hover{transform:rotate(-1deg) translateY(-1px)}
.stamp{font-family:ui-monospace,'SF Mono',monospace;font-size:10px;letter-spacing:.22em;text-transform:uppercase;color:var(--amber);font-weight:800}
.pdf-btn{background:var(--amber);color:var(--ink);border:none;padding:10px 16px;font-weight:800;font-size:12px;letter-spacing:.08em;text-transform:uppercase;cursor:pointer;transition:transform .15s ease,background .15s ease;white-space:nowrap}
.pdf-btn:hover:not(:disabled){transform:translateY(-1px);background:var(--fg)}
.pdf-btn:disabled{opacity:.6;cursor:wait}
@media (max-width:520px){.top-actions{width:100%;justify-content:space-between}}

/* --- PDF export mode: temporarily flatten to a printable light theme so
     html2pdf produces a document that looks intentional on white paper. --- */
body.pdf-mode{background:#FFFFFF!important;color:#0B0806!important}
body.pdf-mode .wrap{max-width:none;padding:0}
body.pdf-mode .top{border-bottom-color:#D4A574;padding-bottom:14px}
body.pdf-mode .brand{background:#0B0806;color:#F1EBDF}
body.pdf-mode .stamp{color:#8C6D3F}
body.pdf-mode .pdf-btn{display:none}
body.pdf-mode h1,body.pdf-mode h2,body.pdf-mode h3{color:#0B0806}
body.pdf-mode .lede,body.pdf-mode .section-note,body.pdf-mode .bullets,body.pdf-mode .commentary{color:#3B3128}
body.pdf-mode .outof{color:#8C6D3F}
body.pdf-mode .summary{color:#3B3128;border-left-color:#D4A574}
body.pdf-mode .section{border-top-color:#E4D5B8;page-break-inside:avoid;break-inside:avoid}
body.pdf-mode .section-h .num{color:#8C6D3F}
body.pdf-mode .role-block h3{color:#8C6D3F}
body.pdf-mode .rewrite{background:#FBF7ED;color:#0B0806;box-shadow:none;border:1px solid #E4D5B8;page-break-inside:avoid;break-inside:avoid}
body.pdf-mode .copy{display:none}
body.pdf-mode .alert{background:#FDECE6;border-color:#E0492B;color:#0B0806}
body.pdf-mode .alert code{background:#FFFFFF;color:#0B0806}
body.pdf-mode .foot{color:#6B5C4A;border-top-color:#E4D5B8}
body.pdf-mode .foot a{color:#8C6D3F}
h1{font-size:clamp(30px,6vw,44px);font-weight:800;letter-spacing:-.03em;line-height:1.05;margin-bottom:14px}
.hero .lede{font-size:16px;color:var(--fg-dim);max-width:44ch;margin-bottom:20px}
.score-row{display:inline-flex;align-items:baseline;gap:8px;margin-bottom:16px}
.score{font-size:80px;font-weight:900;letter-spacing:-.05em;line-height:.9}
.outof{font-family:ui-monospace,'SF Mono',monospace;font-size:11px;letter-spacing:.22em;text-transform:uppercase;color:var(--fg-faint)}
.summary{font-family:Georgia,'Iowan Old Style',serif;font-style:italic;font-size:18px;line-height:1.5;color:var(--fg-dim);padding:16px 0;border-left:2px solid var(--amber);padding-left:16px;margin-top:12px}
.alert{background:rgba(224,73,43,.14);border:1px solid rgba(224,73,43,.35);padding:14px 18px;margin:28px 0;font-size:14px;color:var(--fg)}
.alert code{font-family:ui-monospace,monospace;font-size:12px;background:rgba(0,0,0,.3);padding:2px 6px}
.section{padding:44px 0;border-top:1px solid rgba(241,235,223,.14)}
.section-h{display:flex;align-items:baseline;gap:14px;margin-bottom:18px}
.section-h .num{font-family:ui-monospace,'SF Mono',monospace;font-size:11px;font-weight:800;letter-spacing:.28em;color:var(--amber)}
.section-h .title{font-size:22px;font-weight:800;letter-spacing:-.02em}
.section-note{color:var(--fg-dim);font-size:14px;margin-bottom:20px;max-width:52ch}
.role-block{margin-bottom:26px}
.role-block h3{font-size:15px;font-weight:800;letter-spacing:-.005em;text-transform:uppercase;color:var(--amber);letter-spacing:.14em;font-size:11px;margin-bottom:12px}
.post{margin-bottom:22px}
.post h3{font-size:16px;font-weight:800;margin-bottom:8px}
.rewrite{background:var(--fg);color:var(--ink);padding:18px 20px;margin-bottom:14px;box-shadow:6px 6px 0 rgba(0,0,0,.55);position:relative}
.rewrite-text{font-size:15px;line-height:1.55;white-space:pre-wrap}
.copy{position:absolute;top:12px;right:12px;background:var(--ink);color:var(--amber);border:none;padding:8px 12px;font-family:ui-monospace,monospace;font-size:10px;font-weight:800;letter-spacing:.16em;text-transform:uppercase;cursor:pointer}
.copy:hover{background:#000}
.copy.copied{background:#4A7C59;color:var(--fg)}
.bullets{padding-left:20px;color:var(--fg-dim);font-size:15px;margin-bottom:20px}
.bullets li{margin-bottom:6px;line-height:1.5}
.commentary{font-family:Georgia,serif;font-style:italic;font-size:16px;color:var(--fg-dim);max-width:52ch;margin-bottom:20px}
.cta{display:inline-block;padding:14px 22px;background:var(--amber);color:var(--ink);text-decoration:none;font-weight:800;margin-top:18px}
.foot{margin-top:60px;padding-top:28px;border-top:1px solid rgba(241,235,223,.14);font-size:12px;color:var(--fg-faint);text-align:center}

/* ---- Score breakdown ---- */
.dim-grid{display:grid;gap:22px;margin-top:8px}
.dim{padding:18px 0;border-top:1px solid rgba(241,235,223,.08)}
.dim:first-child{border-top:none;padding-top:0}
.dim-head{display:flex;justify-content:space-between;align-items:baseline;margin-bottom:10px}
.dim-name{font-size:15px;font-weight:800;letter-spacing:-.005em}
.dim-score{font-family:ui-monospace,'SF Mono',monospace;font-weight:900;font-size:20px;color:var(--amber)}
.dim-slash{color:var(--fg-faint);font-weight:700;font-size:12px;letter-spacing:.15em}
.dim-bar{height:4px;background:rgba(241,235,223,.08);position:relative;margin-bottom:12px;overflow:hidden}
.dim-bar-fill{position:absolute;top:0;left:0;bottom:0;background:var(--amber)}
.dim-commentary{font-size:14px;color:var(--fg-dim);line-height:1.5;margin-bottom:8px;max-width:60ch}
.dim-fixes{padding-left:20px;color:var(--fg-dim);font-size:13px;line-height:1.5}
.dim-fixes li{margin-bottom:4px}
body.pdf-mode .dim-bar{background:#E4D5B8}
body.pdf-mode .dim-bar-fill{background:#8C6D3F}
body.pdf-mode .dim-name{color:#0B0806}
body.pdf-mode .dim-score{color:#8C6D3F}
body.pdf-mode .dim-slash{color:#6B5C4A}
body.pdf-mode .dim-commentary,body.pdf-mode .dim-fixes{color:#3B3128}
body.pdf-mode .dim{border-top-color:#E4D5B8}

/* ---- Headline variants ---- */
.variant{margin-bottom:22px}
.variant-angle{font-family:ui-monospace,'SF Mono',monospace;font-size:10px;font-weight:800;letter-spacing:.22em;text-transform:uppercase;color:var(--amber);margin-bottom:8px}
.variant-why{font-size:13px;color:var(--fg-dim);margin-top:8px;line-height:1.5;font-style:italic;max-width:60ch}
body.pdf-mode .variant-angle{color:#8C6D3F}
body.pdf-mode .variant-why{color:#6B5C4A}

/* ---- About full rewrite ---- */
.sub-h{font-size:13px;font-weight:800;letter-spacing:.14em;text-transform:uppercase;color:var(--amber);margin:26px 0 10px}
body.pdf-mode .sub-h{color:#8C6D3F}

/* ---- Interview prep ---- */
.iq{margin-bottom:24px}
.iq-q{font-size:16px;font-weight:800;color:var(--fg);margin-bottom:10px;line-height:1.4}
.iq-grounded{font-size:12px;color:var(--fg-faint);margin-top:8px;font-family:ui-monospace,'SF Mono',monospace;letter-spacing:.06em}
body.pdf-mode .iq-q{color:#0B0806}
body.pdf-mode .iq-grounded{color:#6B5C4A}

/* ---- Recruiter visibility ---- */
.kw{padding:14px 0;border-top:1px solid rgba(241,235,223,.08)}
.kw:first-of-type{border-top:none;padding-top:0}
.kw-head{display:flex;justify-content:space-between;align-items:center;gap:14px;margin-bottom:6px;flex-wrap:wrap}
.kw-word{font-family:ui-monospace,'SF Mono',monospace;font-size:14px;font-weight:800;color:var(--fg)}
.vis-badge{font-family:ui-monospace,'SF Mono',monospace;font-size:10px;font-weight:900;letter-spacing:.2em;text-transform:uppercase;padding:4px 10px;flex-shrink:0}
.vis-badge.on{background:rgba(74,124,89,.24);color:#8DDDA3}
.vis-badge.off{background:rgba(224,73,43,.2);color:#F0A78D}
.kw-reason{font-size:13px;color:var(--fg-dim);line-height:1.5;margin-bottom:4px;max-width:60ch}
.kw-fix{font-size:13px;color:var(--fg);line-height:1.5;max-width:60ch}
.kw-fix strong{color:var(--amber);letter-spacing:.06em;font-family:ui-monospace,monospace;font-size:11px;text-transform:uppercase}
body.pdf-mode .kw{border-top-color:#E4D5B8}
body.pdf-mode .kw-word,body.pdf-mode .kw-fix{color:#0B0806}
body.pdf-mode .kw-reason{color:#3B3128}
body.pdf-mode .kw-fix strong{color:#8C6D3F}
body.pdf-mode .vis-badge.on{background:#DCEDDC;color:#2F5F3F}
body.pdf-mode .vis-badge.off{background:#F8D8CC;color:#7A2E1A}

/* -----------------------------------------------------------------
   PRINT / PDF export
   The Download PDF button triggers window.print(). Users pick "Save
   as PDF" as the destination and get a clean, native-rendered PDF.
   This block flips the page to a light document theme, hides UI
   chrome that has no place on paper, and drops proper page breaks.
   ----------------------------------------------------------------- */
@media print {
  @page { size: A4; margin: 14mm 14mm 18mm 14mm; }
  html, body { background: #FFFFFF !important; color: #0B0806 !important; }
  body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  .wrap { max-width: none !important; padding: 0 !important; }
  .top { border-bottom-color: #D4A574 !important; padding-bottom: 14px !important; }
  .brand { background: #0B0806 !important; color: #F1EBDF !important; }
  .stamp { color: #8C6D3F !important; }
  .pdf-btn, .top-actions .pdf-btn { display: none !important; }
  h1, h2, h3 { color: #0B0806 !important; page-break-after: avoid; break-after: avoid; }
  .lede, .section-note, .bullets, .commentary, .variant-why, .kw-reason { color: #3B3128 !important; }
  .outof { color: #8C6D3F !important; }
  .summary { color: #3B3128 !important; border-left-color: #D4A574 !important; }
  .section {
    border-top-color: #E4D5B8 !important;
    page-break-inside: avoid;
    break-inside: avoid;
    padding: 24px 0 !important;
  }
  .section-h .num, .role-block h3, .variant-angle, .sub-h { color: #8C6D3F !important; }
  .rewrite {
    background: #FBF7ED !important;
    color: #0B0806 !important;
    box-shadow: none !important;
    border: 1px solid #E4D5B8 !important;
    page-break-inside: avoid;
    break-inside: avoid;
  }
  .rewrite-text { color: #0B0806 !important; }
  .copy { display: none !important; }
  .alert { background: #FDECE6 !important; border-color: #E0492B !important; color: #0B0806 !important; }
  .alert code { background: #FFFFFF !important; color: #0B0806 !important; }
  .foot { color: #6B5C4A !important; border-top-color: #E4D5B8 !important; }
  .foot a { color: #8C6D3F !important; }

  /* Score breakdown */
  .dim-bar { background: #E4D5B8 !important; }
  .dim-bar-fill { background: #8C6D3F !important; }
  .dim-name { color: #0B0806 !important; }
  .dim-score { color: #8C6D3F !important; }
  .dim-slash { color: #6B5C4A !important; }
  .dim-commentary, .dim-fixes { color: #3B3128 !important; }
  .dim { border-top-color: #E4D5B8 !important; page-break-inside: avoid; break-inside: avoid; }

  /* Interview prep */
  .iq { page-break-inside: avoid; break-inside: avoid; }
  .iq-q { color: #0B0806 !important; }
  .iq-grounded { color: #6B5C4A !important; }

  /* Recruiter visibility */
  .kw { border-top-color: #E4D5B8 !important; page-break-inside: avoid; break-inside: avoid; }
  .kw-word, .kw-fix { color: #0B0806 !important; }
  .kw-fix strong { color: #8C6D3F !important; }
  .vis-badge.on { background: #DCEDDC !important; color: #2F5F3F !important; }
  .vis-badge.off { background: #F8D8CC !important; color: #7A2E1A !important; }
}
.foot a{color:var(--fg-dim)}
@media (min-width:720px){.wrap{padding:32px 24px 120px}h1{font-size:56px}.top{padding:16px 0 32px}}
</style>`;
}
